### ISSUE TITLE
投资期为0的，应该拒绝发布新文章，时间最好到小时吧，天太长了，也不好测试

### ISSUE THREAD

**Issue by tedyyan** [QOSGroup/qstars#158]
![image](https://user-images.githubusercontent.com/2662290/49980754-bc56a000-ff8f-11e8-8c81-7b3dcf83c75a.png)

**Comment by ms8922** [comment]
增加了投资、竞拍期的时间判断  必须大于0
投资 竞拍 期单位 改为小时
